### ISSUE TITLE
Allow to pass list to PlaylistFromMBIDsPatch

### ISSUE THREAD

**Issue by petitminion** [metabrainz/troi-recommendation-playground#68]
Using troi as a library it could be usefull to allow to pass a list instead of a file in the PlaylistFromMBIDsPatch. 

Could be done like this but maybe its dirty. I didn't find how to pass a list into click argument : 

`core.generate_playlist("playlist-from-mbids", args=[str(list)])`

```
class MBIDReaderElement(Element):
[...]
    def read(self, inputs):

        mbids = []

        if self.filename.startswith("[") and self.filename.endswith("]"):
            for mbid in ast.literal_eval(self.filename):
                print(mbid)
                mbids.append(Recording(mbid=mbid))
        else:
            with open(self.filename, "r") as f:
                for line in f.readlines():
                    if not line:
                        break

                    mbid = line.strip()
                    mbids.append(Recording(mbid=mbid))

        return mbids
```

**Comment by amCap1712** [comment]
Hi! Instead of modifying the existing patch or element, you can create a new a patch and accept mbids as args in it. It should be simple to write it by taking example from existing patches. In any case, we are making some improvements to troi so that its easier to use as a library. Once that is done, I can write up a patch your use case if it helps.

**Comment by petitminion** [comment]
I will do this not worries :) 
thx ! :)
